-- Generated by Mocodo 4.2.12
CREATE TABLE BOITE (
  PRIMARY KEY (numboite),
  numboite varchar(20) NOT NULL,
  nomboite varchar(100),
  annee    int,
  nbpieces int,
  idtheme  int NOT NULL,
  imageB   varchar(200)
);

CREATE TABLE CATEGORIE (
  PRIMARY KEY (idcat),
  idcat  int NOT NULL,
  nomcat varchar(50)
);

CREATE TABLE CONTENIRB (
  PRIMARY KEY (idcont, numboite),
  idcont    int NOT NULL,
  numboite  varchar(20) NOT NULL,
  quantiteb int
);

CREATE TABLE CONTENIRF (
  PRIMARY KEY (idcont, idfig),
  idcont    int NOT NULL,
  idfig     varchar(12) NOT NULL,
  quantitef int
);

CREATE TABLE CONTENIRP (
  PRIMARY KEY (idcont, numpiece, idcoul, en_supplement),
  idcont        int NOT NULL,
  numpiece      varchar(20) NOT NULL,
  idcoul        int NOT NULL,
  en_supplement char(1) NOT NULL,
  quantitep     int
);

CREATE TABLE CONTENU (
  PRIMARY KEY (idcont),
  idcont   int NOT NULL,
  version  int,
  numboite varchar(20),
  idfig varchar(12)
);

CREATE TABLE COULEUR (
  PRIMARY KEY (idcoul),
  idcoul      int NOT NULL,
  nomcoul     varchar(200),
  RGB         varchar(6),
  transparent char(1)
);

CREATE TABLE FIGURINE (
  PRIMARY KEY (idfig),
  idfig     varchar(12) NOT NULL,
  nomfig   varchar(150),
  nbparties int,
  imageF    varchar(200)
);

CREATE TABLE PIECE (
  PRIMARY KEY (numpiece),
  numpiece varchar(20) NOT NULL,
  nompiece varchar(250),
  idcat    int NOT NULL
);

CREATE TABLE THEME (
  PRIMARY KEY (idtheme),
  idtheme   int NOT NULL,
  nomtheme  varchar(50),
  idtheme_pere int NULL
);

ALTER TABLE BOITE ADD FOREIGN KEY (idtheme) REFERENCES THEME (idtheme);

ALTER TABLE CONTENIRB ADD FOREIGN KEY (numboite) REFERENCES BOITE (numboite);
ALTER TABLE CONTENIRB ADD FOREIGN KEY (idcont) REFERENCES CONTENU (idcont);

ALTER TABLE CONTENIRF ADD FOREIGN KEY (idfig) REFERENCES FIGURINE (idfig);
ALTER TABLE CONTENIRF ADD FOREIGN KEY (idcont) REFERENCES CONTENU (idcont);

ALTER TABLE CONTENIRP ADD FOREIGN KEY (idcoul) REFERENCES COULEUR (idcoul);
ALTER TABLE CONTENIRP ADD FOREIGN KEY (numpiece) REFERENCES PIECE (numpiece);
ALTER TABLE CONTENIRP ADD FOREIGN KEY (idcont) REFERENCES CONTENU (idcont);

ALTER TABLE CONTENU ADD FOREIGN KEY (numboite) REFERENCES BOITE (numboite);
ALTER TABLE CONTENU ADD FOREIGN KEY (idfig) REFERENCES FIGURINE (idfig);

ALTER TABLE PIECE ADD FOREIGN KEY (idcat) REFERENCES CATEGORIE (idcat);

ALTER TABLE THEME ADD FOREIGN KEY (idtheme_pere) REFERENCES THEME (idtheme);
