-- | AUTEUR                |
-- | CLASSIFICATION        |
-- | CLIENT                |
-- | COMMANDE              |
-- | DETAILCOMMANDE        |
-- | ECRIRE                |
-- | EDITER                |
-- | EDITEUR               |
-- | LIVRE                 |
-- | MAGASIN               |
-- | POSSEDER              |
-- | THEMES 
-- | CLIENT                |
-- | DETAIL                |
-- | FACTURE               |
-- | PRODUIT           
-- | BOITE                 |
-- | CATEGORIE             |
-- | CONTENIRB             |
-- | CONTENIRF             |
-- | CONTENIRP             |
-- | CONTENU               |
-- | COULEUR               |
-- | FIGURINE              |
-- | PIECE                 |
-- | THEME                 |    
DROP TABLE IF EXISTS PRODUIT CASCADE;
DROP TABLE IF EXISTS BOITE CASCADE;
DROP TABLE IF EXISTS CATEGORIE CASCADE;
DROP TABLE IF EXISTS CONTENIRB CASCADE;
DROP TABLE IF EXISTS CONTENIRF CASCADE;
DROP TABLE IF EXISTS CONTENIRP CASCADE;
DROP TABLE IF EXISTS CONTENU CASCADE;
DROP TABLE IF EXISTS COULEUR CASCADE;
DROP TABLE IF EXISTS FIGURINE CASCADE;
DROP TABLE IF EXISTS PIECE CASCADE;
DROP TABLE IF EXISTS THEME CASCADE;
DROP TABLE IF EXISTS AUTEUR CASCADE;
DROP TABLE IF EXISTS CLASSIFICATION CASCADE;
DROP TABLE IF EXISTS CLIENT CASCADE;
DROP TABLE IF EXISTS COMMANDE CASCADE;
DROP TABLE IF EXISTS DETAILCOMMANDE CASCADE;
DROP TABLE IF EXISTS ECRIRE CASCADE;
DROP TABLE IF EXISTS EDITER CASCADE;
DROP TABLE IF EXISTS EDITEUR CASCADE;
DROP TABLE IF EXISTS LIVRE CASCADE;
DROP TABLE IF EXISTS MAGASIN CASCADE;
DROP TABLE IF EXISTS POSSEDER CASCADE;
DROP TABLE IF EXISTS THEMES CASCADE;
DROP TABLE IF EXISTS CLIENT CASCADE;
DROP TABLE IF EXISTS DETAIL CASCADE;
DROP TABLE IF EXISTS FACTURE CASCADE;


